%% Aggregate objects by image
imgdata = grpstats(datatable,[opt.glme.img_vars opt.gmm.latent_var],{'mean'},'datavars','CellArea');
imgdata.Properties.VariableNames{end} = 'CellArea';

%% Fit model
fixed_effects = [arrayfun(@(x) [x{:} '*'], opt.glme.fixed_effects, 'uni', 0) opt.gmm.latent_var]; % all interaction terms
mdl_formula = ['GroupCount ~ ',fixed_effects{:},opt.glme.random_effects];
mdl.glme = fitglme( imgdata, ...
    mdl_formula, ...
    'Distribution', 'Gamma', 'Link', 'log', ...
    'DummyVarCoding', 'effects', ...
    'FitMethod', 'Laplace', ...
    'Offset', log( imgdata.CellArea ), ...
    'EBMethod', 'TrustRegion2D' ...
    );